let ApiRoute = {
    deleteGym : "api/delete-gym/", //api/delete-gym/12
    newGyms:"api/new-gyms",
    existingGym:'api/existing-gyms',
    feedback:'api/users-feedback',
    seeAllGym:'api/seeall-gyms',
    deleteFeedBack:'api/delete-feedback/',
    addGym:'api/add-gym',
    aproveGym:'api/approve-gym/',
    // Post Apis
    updatePassword:'api/reset-password',
    sendCode:'api/send-code',
    confirmCode:'api/confirm',
    users:'api/users-list',
    deleteUser:'api/delete-user/',
    // GenericApi i-e use for post and get method
    addFaq:'api/faq',
    addProduct:'api/add-product',
faqs:'api/faq',
deleteFaq:'api/faq-delete',
updateFaq:'api/faq-update',
bugs:'api/bugs-list',
deleteBug: 'api/delete-bug/',
gymDetail:'api/gym-detail/',
userDetail:'api/user-profile/',
editFaq:'api/faq-update',
addInfluence:'api/influence',
getInf:'api/influence',
deleteInf:'api/influence/',
infDetail:'api/influence/',
addPartener:'api/partner',
getPartners:'api/partner',
deletePartner:'api/partner/',
partnerDetail:'api/partner/',
addTutorial:'api/tutorial',
getPosts:'api/all-posts',
likePost:'api/actions',
sharePost:'api/share',
addEmp:'add-employee',
contactGym:'api/contact-support',
getFollowings:'api/all-followeing/',
getFollowers:'api/all-follower/',
followPost:'api/follow',
addGymLoc:'api/add-location',
getAllLocs:'api/all-location/',
allCheckInUsers:'api/users-list',
allNotifications:'api/user-notification/',
commentPost:'api/comments',
getAllEmp:'api/all-employee',
getOrders:'api/all-product-order',
getVOrders:'api/all-video-order',
getOrdersP:'api/pending-product-order',
getVOrdersP:'api/pending-video-order',
checkInOut:'api/gym-user-check-history/',
}
export default ApiRoute;